apiVersion: v1
kind: Pod
metadata:
  namespace: default
  name: gael-fio
spec:
  containers:
  - name: fio
    image: gaell/fio-stuff
    imagePullPolicy: Always
    command: ["fio"]
    args:
    - official/ssd-test.fio
    - --directory=/mnt/
    - --runtime=120
  nodeSelector:
    name: mynode
